-- liquibase formatted sql

-- changeset pavelf:1
CREATE TABLE IF NOT EXISTS notification_tasks (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
chat_id bigint NOT NULL,
notification_date_time timestamp NOT NULL,
message varchar NOT NULL
);